# Generated by Django 3.0.5 on 2020-07-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
